# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a65247d60aac536e8d5f6d975e6689e065bdefa6558109ee0d91742a57a489b6c2165ab7ad3df2247a4ae11722c0e2431300a8febcf85e560c4418e22de02cd4

test:
  secret_key_base: 2673e835846438ef39ca3a1b1c54f8bd9658c5f5f681141a930f8814eb851094d3f174fedd699d72aec25ddc6e90a6ba871ff279add9e0c0fc2c04b4ffd1c27b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
